spring:
        application:
              name:ecom-application

        datasource:
          url: jdbc:postgresql://localhost:5432/ecomdb
          username: sa
          password: pass

        jpa:
          database-platform:  org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show-sql: true
        hibernate:
              ddl-auto: update

